import Head from "next/head";
// import Image from "next/image";
// import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.scss";

import Link from "next/link";

import Image from 'next/image'
import imageView from '@assets/images/turkey-view.jpg'
import SimpleSlider from '@components/carousel/carousel'
// import videoView from '/videos/video-views.mp4'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export default function Home() {
  return (
    <>
      <Head>
        <title>Karayaka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.mainImageContainer}>
          {/* <Image 
            src={imageView}
            alt='views of turkey'
            sizes="100vw"
            quality={100}
            fill
            style={{
              objectFit: 'cover',
            }}
            priority 
          /> */}
          <video className={styles.video}
            src='/videos/video-views.mp4'
            loop
            autoPlay
            muted
            preload="auto"   
            // style={{
            //   objectFit: 'cover',
            // }}
          />
        </div>
        <div className={styles.carouselBlock}>
            <p className={styles.blockTitle}>Some city</p>
            <div className={styles.carousel}>
              <SimpleSlider/>
            </div>
            <button className={styles.blockButton}>See all</button>
        </div>
        <div className={styles.carouselBlock}>
        </div>
        <div className={styles.carouselBlock}>
              
        </div>
        <div className={styles.articleBlock}>
            <p className={styles.blockTitle}>Some papers</p> 
            <div className={styles.articleLink}>
              <Image
                className={styles.articleImage}
                src={imageView}
              />  
              <p className={styles.articleDescription}>
                <p className={styles.articleTitle}>articleTitle</p>
                <p className={styles.articleText}> 
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
                  Magni quo porro repellendus numquam aliquid eos iure, reiciendis doloribus. Earum, reprehenderit saepe?
                  Laboriosam quam porro minus at excepturi consequatur sit ducimus.</p>
              </p>
            </div>    
            <div className={styles.articleLink}></div>    
        </div>
      </main>
        <img src="@assets/images/turkey-view.png" alt="" />
    </>
  );
}

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}